pipeline {
    agent any

    parameters {
        string(name: 'SONAR_URL', defaultValue: 'http://13.50.246.94:9000', description: 'SonarQube server URL')
        string(name: 'SONAR_TOKEN', defaultValue: '', description: 'SonarQube authentication token')
    }

    tools {
        maven 'maven3'
        jdk 'jdk17'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                // This command generates the jacoco.xml file needed by Sonar
                sh 'mvn clean install -DskipTests=false'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withEnv(["SONAR_HOST_URL=${params.SONAR_URL}", "SONAR_TOKEN=${params.SONAR_TOKEN}"]) {
                    sh """
                    mvn sonar:sonar \
                        -Dsonar.projectKey=simple-java-maven-app \
                        -Dsonar.host.url=${SONAR_HOST_URL} \
                        -Dsonar.login=${SONAR_TOKEN} \
                        -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
                    """
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline finished."
        }
    }
}
